### ISSUE TITLE
Include the bash script to run the clock in the repo

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/clock#1]
Put a copy of the bash script to run it in the repo itself, along with instruction on how to "install it"

Then instead of having the code directly in (lxdestartup? where isit)

run the script from the repo directly.  Then we can update the script in the repo without having to access the pi.

**Comment by punctuations** [comment]
I can add this tomorrow around 3:00 - 5:00 i can drop by if that works and do it there
