### ISSUE TITLE
Toggle flex on/off

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/clock#6]
Once working, update the Control-panel too.

**Comment by punctuations** [comment]
It is working; I am just adding the control-panel stuff

**Comment by tylerecouture** [comment]
What does it do?

**Comment by punctuations** [comment]
toggleable via touch and removal of files, I will hold off the control panel command until I get the media integrity finished, it that alright?

**Comment by tylerecouture** [comment]
yep!

**Comment by punctuations** [comment]
added fix in [Pull #50](https://github.com/timberline-secondary/hackerspace-scripts-2/pull/50)
